name: 'taxi_rides_ny'
version: '1.0.0'

profile: 'taxi_rides_ny'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  taxi_rides_ny:
    staging:
      materialized: view
    core:
      materialized: table

# 아래 추가
tests:
  taxi_rides_ny:
    assert_positive_fare_amount:
      +severity: warn  # 실패해도 전체 테스트를 중단시키지 않음