# row data가 snowflake의 어느 곳에 위치해 있는지 dbt에게 알려주는 파일

version: 2

sources:
  - name: staging
    database: NY_TAXI
    schema: TRIPDATA
    tables:
      - name: green_tripdata
      - name: yellow_tripdata